media:
  input: assets/uploads
  output: /assets/uploads

content:
  - name: posts
    label: Projects
    path: _posts
    filename: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: sections
        label: Page Sections
        type: list
        summary: "{{layout}} section"
        fields:
          # ─────────────────────────────
          # SECTION LAYOUT
          # ─────────────────────────────
          - name: layout
            label: Select Layout
            type: select
            required: true
            options:
              - label: One Column
                value: one-column
              - label: Two Columns
                value: two-column
          # ─────────────────────────────
          # ONE COLUMN CONTENT
          # ─────────────────────────────
          - name: content
            label: Content
            type: object
            showIf:
              layout: one-column
            fields:
              - name: type
                label: Select Content Type
                type: select
                required: true
                options:
                  - label: Text
                    value: rich-text
                  - label: Image
                    value: image
                  - label: Video
                    value: video
                  - label: Comparison
                    value: comparison

              # TEXT
              - name: text
                label: Text
                type: rich-text
                options:
                  media: false
                showIf:
                  type: rich-text

              # IMAGE
              - name: image
                label: Image
                type: image
                showIf:
                  type: image

              - name: caption
                label: Caption
                type: string
                showIf:
                  type: image

              - name: altText
                label: Alternate Text
                type: string
                showIf:
                  type: image

              # VIDEO
              - name: video_url
                label: Video URL (embed)
                type: string
                showIf:
                  type: video

              - name: video_caption
                label: Video caption
                type: string
                showIf:
                  type: video

              # COMPARISON
              - name: before_image
                label: Before image
                type: image
                showIf:
                  type: comparison

              - name: before_caption
                label: Before Text
                type: string
                showIf:
                  type: comparison

              - name: before_altText
                label: Before Alternate Text
                type: string
                showIf:
                  type: comparison

              - name: after_image
                label: After image
                type: image
                showIf:
                  type: comparison

              - name: after_caption
                label: After Text
                type: string
                showIf:
                  type: comparison

              - name: after_altText
                label: After Alternate Text
                type: string
                showIf:
                  type: comparison

              - name: comparison_caption
                label: Caption
                type: string
                showIf:
                  type: comparison
          # ─────────────────────────────
          # TWO COLUMN — LEFT
          # ─────────────────────────────
          - name: left
            label: Left Column Content
            type: object
            showIf:
              layout: two-column
            fields:
              - name: type
                label: Select Content Type
                type: select
                required: true
                options:
                  - label: Text
                    value: rich-text
                  - label: Image
                    value: image
                  - label: Video
                    value: video
                  - label: Comparison
                    value: comparison

              # TEXT
              - name: text
                label: Text
                type: rich-text
                options:
                  media: false
                showIf:
                  type: rich-text

              # IMAGE
              - name: image
                label: Image
                type: image
                showIf:
                  type: image

              - name: caption
                label: Caption
                type: string
                showIf:
                  type: image

              - name: altText
                label: Alternate Text
                type: string
                showIf:
                  type: image

              # VIDEO
              - name: video_url
                label: Video URL (embed)
                type: string
                showIf:
                  type: video

              - name: video_caption
                label: Video caption
                type: string
                showIf:
                  type: video

              # COMPARISON
              - name: before_image
                label: Before image
                type: image
                showIf:
                  type: comparison

              - name: before_caption
                label: Before Text
                type: string
                showIf:
                  type: comparison

              - name: before_altText
                label: Before Alternate Text
                type: string
                showIf:
                  type: comparison

              - name: after_image
                label: After image
                type: image
                showIf:
                  type: comparison

              - name: after_caption
                label: After Text
                type: string
                showIf:
                  type: comparison

              - name: after_altText
                label: After Alternate Text
                type: string
                showIf:
                  type: comparison

              - name: comparison_caption
                label: Caption
                type: string
                showIf:
                  type: comparison

          # ─────────────────────────────
          # TWO COLUMN — RIGHT
          # ─────────────────────────────
          - name: right
            label: Right Column Content
            type: object
            showIf:
              layout: two-column
            fields:
              - name: type
                label: Select Content Type
                type: select
                required: true
                options:
                  - label: Text
                    value: rich-text
                  - label: Image
                    value: image
                  - label: Video
                    value: video
                  - label: Comparison
                    value: comparison

              # TEXT
              - name: text
                label: Text
                type: rich-text
                options:
                  media: false
                showIf:
                  type: rich-text

              # IMAGE
              - name: image
                label: Image
                type: image
                showIf:
                  type: image

              - name: caption
                label: Caption
                type: string
                showIf:
                  type: image

              - name: altText
                label: Alternate Text
                type: string
                showIf:
                  type: image

              # VIDEO
              - name: video_url
                label: Video URL (embed)
                type: string
                showIf:
                  type: video

              - name: video_caption
                label: Video caption
                type: string
                showIf:
                  type: video

              # COMPARISON
              - name: before_image
                label: Before image
                type: image
                showIf:
                  type: comparison

              - name: before_caption
                label: Before Text
                type: string
                showIf:
                  type: comparison

              - name: before_altText
                label: Before Alternate Text
                type: string
                showIf:
                  type: comparison

              - name: after_image
                label: After image
                type: image
                showIf:
                  type: comparison

              - name: after_caption
                label: After Text
                type: string
                showIf:
                  type: comparison

              - name: after_altText
                label: After Alternate Text
                type: string
                showIf:
                  type: comparison

              - name: comparison_caption
                label: Caption
                type: string
                showIf:
                  type: comparison